Repository antvis/G6, pull requests merged in 2019-12, with the labels that each got.

#995 Internat step3
  docs/manual/middle/elements/edges/arc.en.md
  docs/manual/middle/elements/edges/arc.zh.md
  docs/manual/middle/elements/edges/cubic.en.md
  docs/manual/middle/elements/edges/cubic.zh.md
  docs/manual/middle/elements/edges/defaultEdge.en.md
  docs/manual/middle/elements/edges/defaultEdge.zh.md
  docs/manual/middle/elements/edges/line.en.md
  docs/manual/middle/elements/edges/line.zh.md
  docs/manual/middle/elements/edges/loop.en.md
  docs/manual/middle/elements/edges/loop.zh.md
  docs/manual/middle/elements/edges/polyline.en.md
  docs/manual/middle/elements/edges/polyline.zh.md
  docs/manual/middle/elements/edges/quaratic.en.md
  docs/manual/middle/elements/edges/quaratic.zh.md
  docs/manual/middle/elements/nodes/circle.en.md
  docs/manual/middle/elements/nodes/circle.zh.md
  docs/manual/middle/elements/nodes/defaultNode.en.md
  docs/manual/middle/elements/nodes/diamond.en.md
  docs/manual/middle/elements/nodes/diamond.zh.md
  docs/manual/middle/elements/nodes/ellipse.en.md
  docs/manual/middle/elements/nodes/ellipse.zh.md
  docs/manual/middle/elements/nodes/image.en.md
  docs/manual/middle/elements/nodes/image.zh.md
  docs/manual/middle/elements/nodes/modelRect.en.md
  docs/manual/middle/elements/nodes/modelRect.zh.md
  docs/manual/middle/elements/nodes/rect.en.md
  docs/manual/middle/elements/nodes/rect.zh.md
  docs/manual/middle/elements/nodes/star.en.md
  docs/manual/middle/elements/nodes/star.zh.md
  docs/manual/middle/elements/nodes/traingle.zh.md
  docs/manual/middle/elements/nodes/triangle.en.md
  docs/manual/middle/elements/nodes/triangle.zh.md
  docs/manual/tutorial/behavior.en.md
Labels: PR: unreviewed

#997 fix: g6 types file
  types/antvUtil.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#996 Internat step3
  README-zh_CN.md
  README.md
  docs/api/TreeGraph.zh.md
  docs/api/layout/Graph.en.md
  docs/api/layout/Graph.zh.md
  docs/api/layout/TreeGraph.en.md
  docs/api/layout/TreeGraph.zh.md
  docs/manual/advanced/animation.en.md
  docs/manual/advanced/animation.zh.md
  docs/manual/advanced/create-node-group.en.md
  docs/manual/advanced/custom-behavior.en.md
  docs/manual/advanced/custom-edge.en.md
  docs/manual/advanced/custom-layout.en.md
  docs/manual/advanced/custom-node.en.md
  docs/manual/advanced/graphics-group.en.md
  docs/manual/advanced/iconfont.en.md
  docs/manual/advanced/label-properties.en.md
  docs/manual/advanced/lock-node.en.md
  docs/manual/advanced/lock-node.zh.md
  docs/manual/advanced/mode-and-custom-behavior.en.md
  docs/manual/advanced/shape-and-properties.en.md
  docs/manual/cases/edgeBundling.en.md
  docs/manual/cases/relations.en.md
  docs/manual/cases/sequenceTime.en.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
  docs/manual/middle/g6InReact.en.md
  docs/manual/middle/g6InReact.zh.md
  docs/manual/middle/graph.en.md
  docs/manual/middle/graph.zh.md
  docs/manual/middle/layout.en.md
  docs/manual/middle/layout.zh.md
  docs/manual/middle/nodeGroup.en.md
  docs/manual/middle/nodeGroup.zh.md
  docs/manual/tutorial/animation.en.md
Labels: PR: unreviewed

#998 Internat step3
  docs/api/layout/Graph.en.md
  docs/api/layout/Layout.en.md
  docs/api/nodeEdge/Node.en.md
  docs/api/properties/EdgeProperties.en.md
Labels: PR: unreviewed

#999 fix: loop for rect node
  demos/internal-edge-loop.html
  demos/layout-circular.html
  src/util/graphic.js
Labels: PR: unreviewed, bug

#1000 add: english version for create-node-group doc
  docs/api/Custom.zh.md
  docs/api/properties/EdgeProperties.en.md
  docs/api/properties/TextProperties.en.md
  docs/api/properties/TextProperties.zh.md
  docs/manual/advanced/animation.en.md
  docs/manual/advanced/create-node-group.en.md
  docs/manual/advanced/create-node-group.zh.md
  docs/manual/advanced/custom-behavior.en.md
  docs/manual/advanced/custom-behavior.zh.md
  docs/manual/advanced/custom-edge.en.md
  docs/manual/advanced/custom-edge.zh.md
  docs/manual/advanced/custom-layout.en.md
  docs/manual/advanced/custom-layout.zh.md
  docs/manual/advanced/custom-node.en.md
  docs/manual/advanced/custom-node.zh.md
  docs/manual/advanced/graphics-group.en.md
  docs/manual/advanced/graphics-group.zh.md
  docs/manual/advanced/iconfont.en.md
  docs/manual/advanced/iconfont.zh.md
  docs/manual/advanced/label-properties.en.md
  docs/manual/advanced/label-properties.zh.md
  docs/manual/advanced/shape-and-properties.en.md
  docs/manual/middle/keyConcept.en.md
  docs/manual/middle/nodeGroup.en.md
Labels: PR: unreviewed, add

#1010 Internat step4
  docs/api/nodeEdge/Node.en.md
  docs/api/nodeEdge/Node.zh.md
  docs/api/properties/EdgeProperties.en.md
  docs/api/properties/NodeProperties.en.md
  docs/manual/advanced/create-node-group.en.md
  docs/manual/advanced/custom-behavior.en.md
  docs/manual/advanced/custom-behavior.zh.md
  docs/manual/advanced/lock-node.en.md
  docs/manual/advanced/lock-node.zh.md
  docs/manual/advanced/mode-and-custom-behavior.en.md
  docs/manual/advanced/mode-and-custom-behavior.zh.md
  docs/manual/advanced/shape-and-properties.en.md
  docs/manual/advanced/shape-and-properties.zh.md
  docs/manual/cases/edgeBundling.en.md
  docs/manual/cases/edgeBundling.zh.md
  docs/manual/cases/relations.en.md
  docs/manual/cases/relations.zh.md
  docs/manual/cases/sequenceTime.en.md
  docs/manual/cases/sequenceTime.zh.md
  docs/manual/middle/elements/elementIndex.en.md
  docs/manual/middle/graph.en.md
  docs/manual/middle/layout.zh.md
Labels: PR: unreviewed

#1028 fix: review for cases and FAQ. closes: #1018.
  docs/manual/FAQ/build-error.en.md
  docs/manual/FAQ/build-error.zh.md
  docs/manual/FAQ/front-edge.en.md
  docs/manual/FAQ/front-edge.zh.md
  docs/manual/FAQ/multi-line.zh.md
  docs/manual/FAQ/supportIE.en.md
  docs/manual/FAQ/supportIE.zh.md
  docs/manual/FAQ/updateElement.en.md
  docs/manual/FAQ/updateElement.zh.md
  docs/manual/FAQ/updateText.en.md
  docs/manual/FAQ/updateText.zh.md
  docs/manual/cases/edgeBundling.en.md
  docs/manual/cases/edgeBundling.zh.md
  docs/manual/cases/relations.en.md
  docs/manual/cases/relations.zh.md
  docs/manual/cases/sequenceTime.en.md
  docs/manual/cases/sequenceTime.zh.md
Labels: PR: reviewed-changes-requested, bug

#1029 feat: update types file
  jest.config.js
  package.json
  src/behavior/behavior.ts
  src/behavior/behaviorOption.ts
  src/behavior/drag-canvas.ts
  src/graph/controller/index.ts
  src/graph/controller/mode.ts
  src/graph/graph.ts
  src/graph/tree-graph.ts
  src/interface/behavior.ts
  src/interface/graph.ts
  src/interface/item.ts
  src/item/edge.ts
  src/item/item.ts
  src/item/node.ts
  src/util/base.ts
  src/util/graphic.ts
  src/util/group.ts
  src/util/math.ts
  src/util/path.ts
  tests/unit/behavior/index-spec.ts
  tests/unit/graph/controller/mode-spec.ts
  tsconfig.json
  types/index.ts
Labels: PR: unreviewed, enhancement

#1039 docs: 🔍 Add algolia docsearchOptions
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, documentation

#1038 feat: update graph types and refactor view controller
  demos/assets/data/flare.json
  src/graph/controller/mode.ts
  src/graph/controller/view.ts
  src/graph/graph.ts
  src/interface/graph.ts
  src/util/math.ts
  tests/unit/graph/controller/mode-spec.ts
  types/index.ts
Labels: PR: unreviewed, enhancement

#1044 G6 dev 20191209
  jest.config.js
  package.json
  src/behavior/behaviorOption.ts
  src/graph/controller/event.ts
  src/graph/controller/index.ts
  src/graph/controller/state.ts
  src/graph/graph.ts
  src/interface/behavior.ts
  src/interface/graph.ts
  tests/unit/graph/controller/mode-spec.ts
  types/index.ts
Labels: PR: unreviewed

#1042 docs: Update introduction.zh.md
  docs/manual/introduction.zh.md
Labels: PR: reviewed-approved, documentation

#1043 fix: solved position problem for minimap
  demos/layout-radial-tree.html
  package.json
  plugins/minimap/index.js
Labels: PR: unreviewed, bug

#1053 fix: import g problem. add: behavior ts files
  package.json
  plugins/minimap/index.js
  src/behavior/activate-relations.ts
  src/behavior/brush-select.ts
  src/behavior/click-select.ts
  src/behavior/collapse-expand.ts
  src/behavior/drag-node.ts
  src/behavior/edge-tooltip.ts
  src/behavior/tooltip-base.ts
  src/behavior/tooltip.ts
  src/behavior/zoom-canvas.ts
  src/graph/controller/event.ts
  src/graph/controller/view.ts
  src/interface/behavior.ts
  src/interface/item.ts
  src/interface/shape.ts
  src/item/edge.ts
  src/item/item.ts
  src/item/node.ts
  src/shape/edge.ts
  src/shape/node.ts
  src/shape/nodes/circle.ts
  src/shape/nodes/diamond.ts
  src/shape/nodes/ellipse.ts
  src/shape/nodes/image.ts
  src/shape/nodes/modelRect.ts
  src/shape/nodes/rect.ts
  src/shape/nodes/star.ts
  src/shape/shape.ts
  src/shape/shapeBase.ts
  src/util/graphic.ts
  src/util/math.ts
  tests/unit/shape/edge-spec.ts
  tests/unit/shape/node-spec.ts
  types/index.ts
Labels: PR: unreviewed, bug

#1061 docs: update Plugins.zh.md & Plugins.en.md
  docs/api/Plugins.en.md
  docs/api/Plugins.zh.md
Labels: PR: unreviewed, documentation

#1072 Fix ts errors for util in ts strict mode
  .gitignore
  src/shape/edge.ts
  src/util/graphic.ts
  src/util/group.ts
  src/util/math.ts
  src/util/path.ts
  tests/unit/util/graphic-spec.ts
  tsconfig.json
  types/index.ts
Labels: PR: unreviewed

#1090 fix: 修复G6官网搜索问题
  package.json
Labels: PR: unreviewed, bug

#1098 feat: add tree graph unit test
  .eslintignore
  package.json
  src/graph/graph.ts
  src/interface/graph.ts
  src/shape/nodes/circle.ts
  tests/unit/graph/tree-graph-spec.ts
Labels: PR: unreviewed, enhancement

#1101 Update build tool: using father-build
  package.json
  tsconfig.json
Labels: PR: unreviewed, tool
