Repository antvis/G6, pull requests merged in 2019-11, with the labels that each got.

#897 fix drag-node close autoPaint
  demos/internal-node-rect.html
  src/behavior/drag-node.js
Labels: PR: reviewed-changes-requested

#898 fix: update package version
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, bug

#913 添加GlobalAPI.md、Graph.md
  docs/api/GlobalAPI.md
  docs/api/Graph.md
Labels: PR: unreviewed

#910 Fix: graph.focusItem(item) not working if item is a string
  src/graph/controller/view.js
Labels: Fix, PR: reviewed-changes-requested, PR: unreviewed

#909 fix: optimize the interface declarations
  types/g.d.ts
  types/index.d.ts
Labels: PR: unreviewed, bug

#914 feat: layout parameters support function type
  demos/case-simplify.html
  demos/layout-dagre.html
  demos/layout-force.html
  package.json
  src/global.js
  src/layout/dagre.js
  src/layout/force.js
  src/layout/fruchterman-group.js
  src/layout/fruchterman.js
  src/layout/radial/radial.js
  src/layout/radial/radialNonoverlapForce.js
Labels: PR: unreviewed, enhancement

#915 fix: polyline not support options styles
  .gitignore
  demos/fix-behavior.html
  demos/internal-edges.html
  src/behavior/brush-select.js
  src/shape/edges/polyline.js
Labels: PR: unreviewed, bug

#917 fix: merge custom label config
  src/shape/edges/polyline.js
Labels: PR: reviewed-changes-requested, bug

#920 docs: scatter demos
  examples/scatter/default/demo/default.js
  examples/scatter/default/demo/meta.json
  examples/scatter/default/index.zh.md
  examples/scatter/hover/demo/hover.js
  examples/scatter/hover/demo/meta.json
  examples/scatter/hover/index.zh.md
  examples/scatter/node/demo/meta.json
  examples/scatter/node/demo/node.js
  examples/scatter/node/index.zh.md
  examples/scatter/position/demo/meta.json
  examples/scatter/position/demo/position.js
  examples/scatter/position/index.zh.md
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested, documentation

#918 fix: fix the interface of the `on` method
  types/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#928 fix: version number
  package.json
  src/behavior/brush-select.js
  src/global.js
  src/graph/controller/customGroup.js
  src/graph/controller/event.js
  src/graph/graph.js
  src/layout/circular.js
  src/layout/concentric.js
  src/layout/fruchterman-group.js
  src/layout/fruchterman.js
  src/layout/grid.js
  src/layout/radial/radial.js
  src/layout/random.js
Labels: PR: reviewed-changes-requested, bug

#929 fix: G6 package delete public and .cache file
  .npmignore
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, bug

#930 Minimap 优化
  package.json
  plugins/minimap/index.js
Labels: PR: unreviewed

#932 Update index.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested

#936 Fix minimap state 20191120
  .eslintignore
  src/behavior/drag-node.js
  src/graph/controller/state.js
  src/shape/nodes/circle.js
  src/shape/nodes/diamond.js
  src/shape/nodes/ellipse.js
  src/shape/nodes/modelRect.js
  src/shape/nodes/rect.js
Labels: PR: reviewed-changes-requested

#940 Fix minimap state 20191120
  package.json
  src/global.js
  src/shape/nodes/modelRect.js
Labels: PR: reviewed-changes-requested

#931 Feat: support layout using web worker
  demos/case-simplify.html
  demos/layout-circular-web-worker.html
  demos/layout-data-translation-web-worker.html
  demos/layout-force-timing-web-worker.html
  demos/layout-force-web-worker.html
  demos/layout-fruchterman-web-worker.html
  demos/layout-method-translation-web-worker.html
  package.json
  src/graph/controller/layout.js
  src/graph/graph.js
  src/layout/force.js
  src/layout/layout.js
  src/layout/mds.js
  src/layout/radial/radial.js
  src/layout/worker/layout.worker.js
  src/layout/worker/layoutConst.js
  src/util/layout.js
  src/util/math.js
  test/unit/layout/circular-web-worker-spec.js
  test/unit/layout/force-web-worker-spec.js
  test/unit/layout/web-worker-spec.js
  webpack.config.js
Labels: Feat, PR: reviewed-changes-requested, PR: unreviewed

#933 fix:missing cache ucfirst
  src/shape/shape.js
Labels: PR: unreviewed

#945 Pre 1122
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested

#942 🚀 g6.antv.vision
  gatsby-config.js
  package.json
Labels: PR: unreviewed

#947 test: fix babel-preset-gatsby
  .babelrc
  .babelrc.js
  .travis.yml
Labels: PR: unreviewed, test

#948 Pre 1122
  package.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested

#952 Pre 1122
  package.json
Labels: PR: unreviewed

#956 fix: update docs url
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested, bug

#957 fix: delete sankey
  examples/net/sankey/demo/meta.json
  examples/net/sankey/demo/sankey.js
  examples/net/sankey/index.en.md
  examples/net/sankey/index.zh.md
Labels: PR: reviewed-changes-requested, bug

#958 fix: not include corejs
  .babelrc
  .babelrc.js
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, bug

#959 fix: webworker for case simplify
  examples/case/simplifyCluster/demo/index.js
  gatsby-browser.js
Labels: PR: reviewed-changes-requested, bug

#961 fix: babelrc support gatsby
  .babelrc.js
  package.json
Labels: PR: reviewed-changes-requested, bug

#963 fix: remove wrong title
  package.json
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#964 fix: G6 home page add titlesuffix
  site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#965 fix: g6 type files
  docs/manual/cases/relations.en.md
  docs/manual/cases/relations.zh.md
  docs/manual/cases/sequenceTime.en.md
  docs/manual/cases/sequenceTime.zh.md
  types/antvUtil.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#966 feat: declare antv/util typings
  types/antvUtil.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested, enhancement

#969 fix: update package version number
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, bug

#970 Fix an issue that graph is not refreshed when calling graph.changeData method
  demos/layout-preset-change-data.html
  src/graph/controller/layout.js
  src/graph/graph.js
  test/unit/layout/circular-web-worker-spec.js
  test/unit/layout/force-web-worker-spec.js
  test/unit/layout/preset-spec.js
  test/unit/layout/web-worker-spec.js
Labels: PR: reviewed-changes-requested

#971 fix: group position error
  CHANGELOG.md
  package.json
  src/global.js
  src/graph/graph.js
Labels: PR: unreviewed, bug

#975 feat: english version of API
  docs/api/Behavior.en.md
  docs/api/Behavior.zh.md
  docs/api/Custom.en.md
  docs/api/Custom.zh.md
  docs/api/Event.en.md
  docs/api/Event.zh.md
  docs/api/GlobalAPI.zh.md
  docs/api/Graph.en.md
  docs/api/Graph.zh.md
  docs/api/Group.en.md
  docs/api/Group.zh.md
  docs/api/Item.zh.md
  docs/api/Shape.en.md
  docs/api/Shape.zh.md
  docs/api/TreeGraph.en.md
  docs/api/TreeGraph.zh.md
  docs/api/nodeEdge/Edge.en.md
  docs/api/nodeEdge/Edge.zh.md
  docs/api/nodeEdge/Item.en.md
  docs/api/nodeEdge/Item.zh.md
  docs/api/nodeEdge/Node.en.md
  docs/api/nodeEdge/Node.zh.md
  docs/api/properties/EdgeProperties.en.md
  docs/api/properties/EdgeProperties.zh.md
  docs/api/properties/NodeProperties.en.md
  docs/api/properties/NodeProperties.zh.md
  docs/api/properties/TextProperties.en.md
  docs/api/properties/TextProperties.zh.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested, enhancement

#976 fix: small error of english version of treegraph
  docs/api/TreeGraph.en.md
Labels: PR: reviewed-changes-requested, bug

#973 fix typescript compile error
  types/antvUtil.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested

#979 fix: update g6 version
  docs/manual/getting-started.zh.md
Labels: PR: unreviewed, bug

#978 Internationalization
  README-zh_CN.md
  README.md
  docs/api/Behavior.en.md
  docs/api/Behavior.zh.md
  docs/api/Custom.en.md
  docs/api/Event.en.md
  docs/api/Graph.en.md
  docs/api/Group.en.md
  docs/api/Group.zh.md
  docs/api/layout/Graph.en.md
  docs/api/layout/Graph.zh.md
  docs/api/layout/Layout.en.md
  docs/api/layout/TreeGraph.en.md
  docs/api/layout/TreeGraph.zh.md
  docs/api/nodeEdge/Edge.en.md
  docs/api/nodeEdge/Item.en.md
  docs/api/nodeEdge/Item.zh.md
  docs/api/nodeEdge/Node.en.md
  docs/api/properties/EdgeProperties.en.md
  docs/api/properties/NodeProperties.en.md
  docs/api/properties/TextProperties.en.md
  docs/api/properties/TextProperties.zh.md
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
  examples/net/concentricLayout/API.en.md
  examples/net/gridLayout/API.en.md
  examples/tree/compactBox/API.en.md
  examples/tree/dendrogram/API.en.md
  examples/tree/indented/API.en.md
  examples/tree/mindmap/API.en.md
Labels: PR: unreviewed

#980 feat: update introduction docs
  README-zh_CN.md
  README.md
  docs/manual/introduction.en.md
  docs/manual/introduction.zh.md
Labels: PR: unreviewed, enhancement

#981 fix: g6 site demos
  package.json
  types/antvUtil.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#983 fix: g6 site error
  src/graph/controller/item.js
  src/util/base.js
  types/antvUtil.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#982 add: english files for tutorial
  docs/manual/getting-started.en.md
  docs/manual/tutorial/animation.en.md
  docs/manual/tutorial/animation.zh.md
  docs/manual/tutorial/behavior.en.md
  docs/manual/tutorial/behavior.zh.md
  docs/manual/tutorial/elements.en.md
  docs/manual/tutorial/elements.zh.md
  docs/manual/tutorial/epilog.en.md
  docs/manual/tutorial/epilog.zh.md
  docs/manual/tutorial/example.en.md
  docs/manual/tutorial/example.zh.md
  docs/manual/tutorial/layout.en.md
  docs/manual/tutorial/layout.zh.md
  docs/manual/tutorial/plugins.en.md
  docs/manual/tutorial/plugins.zh.md
  docs/manual/tutorial/preface.en.md
  docs/manual/tutorial/preface.zh.md
Labels: PR: reviewed-changes-requested, add

#985 fix: delete sanky lib
  gatsby-browser.js
Labels: PR: reviewed-changes-requested, bug

#989 Update g6 site
  docs/manual/FAQ/build-error.en.md
  docs/manual/FAQ/build-error.zh.md
  docs/manual/FAQ/front-edge.en.md
  docs/manual/FAQ/front-edge.zh.md
  docs/manual/FAQ/multi-line.en.md
  docs/manual/FAQ/multi-line.zh.md
Labels: PR: reviewed-changes-requested

#990 Internat step2
  docs/api/layout/Layout.en.md
  docs/manual/getting-started.en.md
  docs/manual/tutorial/animation.en.md
  docs/manual/tutorial/animation.zh.md
  docs/manual/tutorial/behavior.en.md
  docs/manual/tutorial/behavior.zh.md
  docs/manual/tutorial/elements.en.md
  docs/manual/tutorial/elements.zh.md
  docs/manual/tutorial/epilog.en.md
  docs/manual/tutorial/epilog.zh.md
  docs/manual/tutorial/example.en.md
  docs/manual/tutorial/example.zh.md
  docs/manual/tutorial/layout.en.md
  docs/manual/tutorial/layout.zh.md
  docs/manual/tutorial/plugins.en.md
  docs/manual/tutorial/plugins.zh.md
  docs/manual/tutorial/preface.en.md
Labels: PR: unreviewed

#993 Internat step3
  docs/api/Group.en.md
  docs/manual/middle/elements/edgeVisible.en.md
  docs/manual/middle/elements/edgeVisible.zh.md
  docs/manual/middle/elements/elementIndex.en.md
  docs/manual/middle/elements/elementIndex.zh.md
  docs/manual/middle/elements/nodes/circle.en.md
  docs/manual/middle/elements/nodes/circle.zh.md
  docs/manual/middle/elements/nodes/defaultNode.en.md
  docs/manual/middle/elements/nodes/defaultNode.zh.md
  docs/manual/middle/elements/nodes/diamond.en.md
  docs/manual/middle/elements/nodes/diamond.zh.md
  docs/manual/middle/elements/nodes/ellipse.en.md
  docs/manual/middle/elements/nodes/ellipse.zh.md
  docs/manual/middle/elements/nodes/image.en.md
  docs/manual/middle/elements/nodes/image.zh.md
  docs/manual/middle/elements/nodes/modelRect.en.md
  docs/manual/middle/elements/nodes/modelRect.zh.md
  docs/manual/middle/elements/nodes/rect.en.md
  docs/manual/middle/elements/nodes/rect.zh.md
  docs/manual/middle/elements/nodes/star.en.md
  docs/manual/middle/elements/nodes/star.zh.md
  docs/manual/middle/elements/nodes/traingle.en.md
  docs/manual/middle/elements/nodes/traingle.zh.md
  docs/manual/middle/keyConcept.en.md
  docs/manual/middle/keyConcept.zh.md
Labels: PR: reviewed-changes-requested
