Repository antvis/G6, pull requests merged in 2019-09, with the labels that each got.

#823 fix: drag group node
  demos/area-chart-node.html
  demos/bar-chart-node.html
  demos/chart-node.html
  demos/collapse-expand-group.html
  demos/custom-tree-interactive.html
  demos/front-edge.html
  demos/line-chart-node.html
  demos/point-chart-node.html
  demos/stacked-bar-chart-node.html
  package.json
  src/behavior/drag-group.js
  src/behavior/drag-node-with-group.js
  src/behavior/drag-node.js
  src/graph/controller/customGroup.js
  src/graph/graph.js
  test/unit/graph/controller/custom-group-spec.js
Labels: PR: reviewed-changes-requested, bug

#723 feat: Behavior collapse-expand增加支持自定义单击或双击触发
  src/behavior/collapse-expand.js
  src/behavior/zoom-canvas.js
  test/unit/graph/tree-graph-spec.js
Labels: PR: unreviewed, enhancement

#824 update package version
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested

#830 Dev3.0.5
  demos/drag-group.html
  package.json
  src/global.js
  src/graph/controller/customGroup.js
Labels: PR: reviewed-changes-requested

#831 getModel is undefined
  src/graph/tree-graph.js
Labels: PR: reviewed-changes-requested

#834 Dev3.0.5
  demos/circle-group.html
  demos/rect-group.html
  package.json
  src/behavior/drag-group.js
  src/behavior/drag-node-with-group.js
  src/behavior/drag-node.js
  src/global.js
  src/graph/controller/customGroup.js
  test/unit/graph/controller/custom-group-spec.js
Labels: PR: unreviewed

#841 fix group data not support es5
  CHANGELOG.md
  package.json
  src/global.js
  src/util/groupData.js
  test/unit/graph/controller/custom-group-spec.js
  test/unit/index-spec.js
  test/unit/util/groupdata-spec.js
Labels: PR: reviewed-changes-requested

#855 change shape color
  src/global.js
  src/shape/nodes/circle.js
  src/shape/nodes/diamond.js
  src/shape/nodes/ellipse.js
  src/shape/nodes/rect.js
  src/shape/nodes/star.js
  src/shape/nodes/triangle.js
  test/bugs/issue-659-spec.js
Labels: PR: unreviewed
