Repository antvis/G6, pull requests merged in 2019-10, with the labels that each got.

#857 修复当自定义的节点中心位置不在中心点时delegate错位的问题
  demos/custom-node-card.html
  src/behavior/drag-node.js
Labels: PR: reviewed-changes-requested

#859 fix: case simplify edge stroke problem. feat: abilities of G6 are rev…
  README-zh_CN.md
  README.md
  demos/case-beijing-metro-animation.html
  demos/case-simplify.html
Labels: PR: unreviewed, bug

#861 Demo improve
  demos/case-beijing-metro-animation.html
  demos/case-multi-subgraph-layout.html
  demos/interact-state.html
  demos/internal-edge-arc.html
  demos/layout-circular-divisions.html
  demos/layout-circular-spiral.html
  demos/layout-circular.html
  demos/layout-custom-bigraph.html
  demos/layout-custom.html
  demos/layout-default-random.html
  demos/layout-expand-nodes.html
  demos/layout-force-drag-fix.html
  demos/layout-force-timing.html
  demos/layout-fruchterman.html
  demos/layout-large-tree.html
  demos/layout-mds.html
  demos/layout-radial-tree.html
  demos/layout-radial.html
  demos/layout-subgraph.html
  demos/mapping-visual.html
  demos/others-arc-diagram.html
  demos/others-bubbles.html
  demos/others-circular-arc-diagram.html
  demos/others-file-system.html
  demos/others-interactive-custom-tree.html
  demos/others-sankey-diagram.html
  demos/tree-change-view.html
  demos/tree-cloudatlas.html
  demos/tree-custom.html
  demos/tree-node-issue.html
  src/graph/graph.js
  test/unit/graph/graph-spec.js
Labels: PR: unreviewed

#865 修复fitView网格空白问题
  plugins/grid/index.js
Labels: PR: reviewed-changes-requested

#868 Dev3.1.0
  CHANGELOG.md
  demos/group-circle.html
  demos/group-rect.html
  demos/internal-edges.html
  demos/internal-node-rect.html
  demos/internal-node-star.html
  demos/layout-force.html
  package.json
  plugins/grid/index.js
  src/behavior/activate-relations.js
  src/behavior/brush-select.js
  src/behavior/click-select.js
  src/behavior/collapse-expand-group.js
  src/behavior/collapse-expand.js
  src/behavior/drag-canvas.js
  src/behavior/drag-group.js
  src/behavior/drag-node-with-group.js
  src/behavior/drag-node.js
  src/global.js
  src/graph/controller/customGroup.js
  src/graph/controller/item.js
  src/index.js
  src/layout/circular.js
  src/layout/fruchterman.js
  src/layout/radial/radial.js
  src/layout/random.js
  src/shape/nodes/circle.js
  src/shape/nodes/diamond.js
  src/shape/nodes/ellipse.js
  src/shape/nodes/modelRect.js
  src/shape/nodes/rect.js
  src/shape/nodes/star.js
  src/shape/nodes/triangle.js
  test/unit/graph/controller/custom-group-spec.js
Labels: PR: unreviewed

#886 fix: replace g2 to g6 for contributing.md
  CONTRIBUTING.md
  CONTRIBUTING.zh-CN.md
Labels: PR: unreviewed, bug

#878 feat: add g6 type definition
  package.json
  types/g.d.ts
  types/index.d.ts
Labels: PR: reviewed-changes-requested, enhancement

#887 Dev3.1.0
  demos/internal-node-ellipse.html
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested

#890 fix not support ie11
  .browserslistrc
  package.json
Labels: PR: unreviewed

#891 feat: update definition file
  types/index.d.ts
Labels: PR: reviewed-changes-requested

#893 fix brush-select and drag-group behavior
  CHANGELOG.md
  demos/group-rect.html
  demos/internal-node-rect.html
  demos/internal-node-star.html
  demos/system-graph-demo.html
  src/behavior/brush-select.js
  src/behavior/drag-group.js
  src/shape/edge.js
  src/shape/edges/polyline.js
Labels: PR: reviewed-changes-requested
