Repository antvis/G6, pull requests merged in 2020-03, with the labels that each got.

#1281 feat: optimize the interfaces of g6
  src/behavior/behavior.ts
  src/graph/graph.ts
  src/interface/behavior.ts
  src/interface/graph.ts
  src/interface/item.ts
  src/interface/shape.ts
  src/types/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#1306 docs: complete the missing CHANGELOG for 3.2.3 to 3.2.7.
  .travis.yml
  docs/api/shapeProperties.en.md
  docs/api/shapeProperties.zh.md
  docs/manual/middle/elements/edges/defaultEdge.en.md
  docs/manual/middle/elements/edges/defaultEdge.zh.md
  docs/manual/middle/elements/nodes/defaultNode.en.md
  docs/manual/middle/elements/nodes/defaultNode.zh.md
Labels: documentation

#1308 chore: fix typo
  src/layout/dagre.ts
  src/layout/radial/radial.ts
Labels: PR: unreviewed, chore

#1326 fix: empty path string when startpoint and endpoint is nan in polyline
  package.json
  src/shape/edges/polyline.ts
  tests/unit/layout/dagre-spec.ts
Labels: PR: unreviewed, bug

#1370 feat: config the paddings and smallest size for rect and circle.
  src/global.ts
  src/graph/graph.ts
  src/shape/combo.ts
  src/shape/combos/circle.ts
  src/shape/combos/rect.ts
  src/types/index.ts
  stories/Combo/component/default-combo.tsx
  tests/unit/shape/combo-spec.ts
Labels: PR: unreviewed, enhancement
