Repository antvis/G6, pull requests merged in 2020-08, with the labels that each got.

#1875 fix: clear not clean combos.
  src/graph/graph.ts
Labels: PR: unreviewed, bug

#1889 feat: new syntax for xml node with easier usage.
  src/interface/shape.ts
  src/shape/shape.ts
  src/shape/xml.ts
  stories/Shape/component/xml.tsx
  stories/Shape/shape.stories.tsx
  tests/unit/shape/nodes/xml-spec.ts
Labels: PR: unreviewed, enhancement

#1904 docs: add Graph Config
  docs/api/G6/GraphConfig.en.md
  docs/api/G6/GraphConfig.zh.md
  docs/api/G6/GraphMethod.zh.md
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, documentation

#1906 docs: add Graph Config for english
  docs/api/G6/GraphConfig.en.md
  docs/api/G6/GraphConfig.zh.md
  docs/api/G6/GraphMethod.en.md
  docs/api/G6/GraphMethod.zh.md
Labels: PR: unreviewed, documentation

#1900 fix: self-loop / root node cycle detection in undirected graph
  src/algorithm/detect-cycle.ts
Labels: PR: reviewed-changes-requested, bug

#1911 fix: grid plugin dom class name.
  package.json
  src/plugins/grid/index.ts
Labels: PR: unreviewed, bug

#1912 fix: handleMenuClick trigger multiple times
  src/plugins/menu/index.ts
Labels: PR: reviewed-changes-requested, bug

#1914 feat: xml node adapt named style
  src/shape/xml.ts
  stories/Shape/component/xml.tsx
  tests/unit/shape/nodes/xml-spec.ts
Labels: PR: unreviewed, enhancement

#1923 fix: menu plugin clickHandler problem
  src/plugins/menu/index.ts
Labels: PR: unreviewed, bug

#1928 fix: arrow state & linkpoint
  package.json
  src/behavior/click-select.ts
  src/behavior/collapse-expand-combo.ts
  src/behavior/drag-combo.ts
  src/behavior/drag-node.ts
  src/behavior/tooltip-base.ts
  src/shape/nodes/circle.ts
  src/shape/nodes/diamond.ts
  src/shape/nodes/ellipse.ts
  src/shape/nodes/modelRect.ts
  src/shape/nodes/rect.ts
  src/shape/nodes/star.ts
  src/shape/nodes/triangle.ts
  src/shape/shapeBase.ts
  stories/Shape/component/polyline.tsx
  tests/unit/state/update-element-states-spec.ts
Labels: PR: unreviewed, bug

#1916 fix: xml node state style not correct
  src/shape/shape.ts
  src/shape/xml.ts
  stories/Shape/component/xml.tsx
Labels: PR: unreviewed, bug

#1926 docs: update changelog & version number
  CHANGELOG.md
  package.json
  src/global.ts
Labels: PR: unreviewed, documentation

#1929 feat: find all paths and the shortest path between two nodes
  package.json
  src/algorithm/dijkstra.ts
  src/algorithm/find-path.ts
  src/algorithm/index.ts
  stories/Algorithm/algo.stories.tsx
  stories/Algorithm/component/path.tsx
  tests/unit/algorithm/find-path-spec.ts
Labels: PR: unreviewed, enhancement

#1883 feat: add minimum spanning tree algorithm
  package.json
  src/algorithm/index.ts
  src/algorithm/mst.ts
  src/algorithm/structs/binary-heap/index.ts
  src/algorithm/structs/union-find/index.ts
  tests/unit/algorithm/mst-spec.ts
Labels: PR: unreviewed, enhancement

#1932 chore: 🆙 upgrade worker-loader to 3.x
  package.json
  webpack.config.js
Labels: PR: unreviewed, chore

#1933 test: add surge-preview action
  .github/workflows/preview.yml
Labels: PR: unreviewed, test

#1934 chore: add rebase action
  .github/workflows/rebase.yml
Labels: PR: unreviewed, chore

#1942 fix: xml node parse error and origin style only used on keyshape
  src/shape/xml.ts
  stories/Shape/component/xml.tsx
Labels: PR: unreviewed, bug

#1949 Update index.ts
  examples/case/decisionTree/demo/index.ts
Labels: PR: unreviewed

#1960 fix: xml node surport image node
  src/shape/xml.ts
  stories/Shape/component/xml.tsx
Labels: PR: unreviewed, bug

#1962 feat: add smart tip for g6 code
  api-extractor.json
  src/api.ts
Labels: PR: unreviewed, enhancement

#1968 fix: img state
  package.json
  src/item/item.ts
Labels: PR: unreviewed, bug

#1973 feat: docs & demos of chart node
  api-extractor.json
  docs/manual/middle/jsx-node.en.md
  docs/manual/middle/jsx-node.zh.md
  examples/item/customNode/demo/meta.json
  examples/item/customNode/demo/pieChartNode.js
  examples/item/customNode/demo/pointChart.js
  src/api.ts
  stories/Shape/component/interval-chart.tsx
  stories/Shape/component/line-chart.tsx
  stories/Shape/component/multi-chart.tsx
  stories/Shape/component/pie-chart.tsx
  stories/Shape/component/point-chart.tsx
  stories/Shape/component/xml.tsx
Labels: PR: reviewed-changes-requested, enhancement

#1991 docs: update the english version of jsx-node doc.
  docs/manual/middle/jsx-node.en.md
  docs/manual/middle/jsx-node.zh.md
Labels: PR: unreviewed, documentation

#1989 fix: docs for getConnectedComponents;fix:example title for create edge
  docs/api/Algorithm.en.md
  docs/api/Algorithm.zh.md
  examples/interaction/createEdge/index.en.md
Labels: PR: unreviewed, bug

#1987 test: graph-hull-spec, math-spec
  src/graph/graph.ts
  src/shape/hull/bubbleset.ts
  src/util/math.ts
  src/util/path.ts
  tests/unit/graph/graph-hull-spec.ts
  tests/unit/shape/hull/bubble-spec.ts
  tests/unit/util/math-spec.ts
Labels: PR: unreviewed, test

#1988 feat: pagerank algorithm
  docs/api/Algorithm.en.md
  docs/api/Algorithm.zh.md
  src/algorithm/index.ts
  src/algorithm/pagerank.ts
  src/interface/graph.ts
  stories/Algorithm/algo.stories.tsx
  stories/Algorithm/component/pagerank.tsx
  tests/unit/algorithm/pagerank-spec.ts
Labels: PR: unreviewed, enhancement

#2014 fix: create-edge behavior & stack docs
  docs/api/Graph.en.md
  docs/api/Graph.zh.md
  src/behavior/create-edge.ts
  tests/unit/behavior/create-edge-spec.ts
Labels: PR: unreviewed, bug
