Repository antvis/G6, pull requests merged in 2020-01, with the labels that each got.

#1110 feat：plugins重构 & build梳理
  .babelrc.js
  .eslintignore
  .eslintrc
  .eslintrc.js
  .fatherrc.js
  .gitignore
  .prettierrc
  .prettierrc.js
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  package.json
  plugins/base.js
  plugins/bundling/index.js
  plugins/grid/index.js
  plugins/index.js
  plugins/minimap/index.js
  src/graph/controller/customGroup.ts
  src/graph/controller/event.ts
  src/graph/controller/item.ts
  src/graph/graph.ts
  src/graph/tree-graph.ts
  src/interface/graph.ts
  src/plugins/base.ts
  src/plugins/bundling/index.ts
  src/plugins/grid/index.ts
  src/plugins/index.ts
  src/plugins/menu/index.ts
  src/plugins/minimap/index.ts
  stories/Shape/component/default-shape.tsx
  stories/Shape/shape.stories.tsx
  stories/index.stories.tsx
  tests/unit/graph/graph-spec.ts
  tests/unit/plugins/grid-spec.ts
  tests/unit/plugins/menu-spec.ts
  tsconfig.json
  tslint.json
  types/index.ts
  webpack.config.js
Labels: PR: unreviewed

#1116 fix: empty data event tigger error
  src/graph/controller/event.js
  src/graph/controller/view.js
  src/util/base.js
Labels: PR: unreviewed, bug

#1122 Select emit
  src/behavior/brush-select.ts
  src/behavior/click-select.ts
  tests/unit/behavior/select-spec.ts
Labels: PR: unreviewed

#1124 Feat/empty group position：新增空节点可拖动
  src/graph/controller/customGroup.js
Labels: PR: reviewed-changes-requested

#1125 feat: update package version
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, enhancement

#1126 fix：增加plugins、util及graph等模块的单测
  package.json
  src/graph/controller/item.ts
  src/graph/controller/state.ts
  src/graph/graph.ts
  src/interface/graph.ts
  src/plugins/bundling/index.ts
  src/plugins/menu/index.ts
  src/plugins/minimap/index.ts
  src/util/math.ts
  src/util/path.ts
  tests/unit/graph/controller/customGroup-spec.ts
  tests/unit/graph/controller/state-spec.ts
  tests/unit/graph/graph-spec.ts
  tests/unit/graph/tree-graph-spec.ts
  tests/unit/layout/circular-spec.ts
  tests/unit/layout/circular-web-worker-spec.ts
  tests/unit/layout/force-web-worker-spec.ts
  tests/unit/layout/grid-spec.ts
  tests/unit/layout/mds-spec.ts
  tests/unit/layout/preset-spec.ts
  tests/unit/layout/random-spec.ts
  tests/unit/layout/web-worker-spec.ts
  tests/unit/plugins/bundling-spec.ts
  tests/unit/plugins/menu-spec.ts
  tests/unit/plugins/minimap-spec.ts
  tests/unit/util/base-spec.ts
  tests/unit/util/math-spec.ts
  tests/unit/util/path-spec.ts
  tests/unit/util/timeOut.ts
  types/index.ts
Labels: PR: unreviewed

#1129 Fix/dagre
  src/layout/dagre.js
  test/unit/layout/dagre-spec.js
Labels: PR: reviewed-changes-requested

#1141 fix: add name for built-in shapes. fix: demos problem of the site. fi…
  examples/case/christmasBubbles/demo/christmasBubbles.js
  examples/interaction/loadData/demo/loadTreeData.js
  examples/interaction/nodeGroup/demo/circle.js
  examples/interaction/nodeGroup/demo/rect.js
  examples/interaction/partialResponse/demo/partialNode.js
  examples/interaction/position/demo/move.js
  examples/net/forceDirected/demo/forceDirectedFunctionalParams.js
  examples/scatter/edge/demo/edge.js
  examples/scatter/edge/demo/lineGrowth.js
  examples/scatter/node/demo/node.js
  examples/shape/customEdge/demo/customPolyline.js
  examples/shape/customNode/demo/card.js
  examples/tool/contextMenu/demo/contextMenu.js
  examples/tool/tooltip/demo/tooltip.js
  examples/tree/indented/demo/filesystem.js
  package.json
  src/behavior/brush-select.ts
  src/behavior/collapse-expand.ts
  src/behavior/drag-group.ts
  src/behavior/drag-node-with-group.ts
  src/behavior/drag-node.ts
  src/graph/controller/customGroup.ts
  src/graph/graph.ts
  src/index.ts
  src/plugins/minimap/index.ts
  src/shape/edge.ts
  src/shape/edges/polyline.ts
  src/shape/node.ts
  src/shape/nodes/circle.ts
  src/shape/nodes/diamond.ts
  src/shape/nodes/ellipse.ts
  src/shape/nodes/image.ts
  src/shape/nodes/modelRect.ts
  src/shape/nodes/rect.ts
  src/shape/nodes/star.ts
  src/shape/nodes/triangle.ts
  src/shape/shapeBase.ts
  src/util/base.ts
  src/util/graphic.ts
  src/util/index.ts
  stories/Interaction/component/view-port.tsx
  stories/Interaction/interaction.stories.tsx
  stories/Performance/component/node-amount.tsx
  stories/Tree/component/file-system.tsx
  stories/Tree/tree.stories.tsx
  stories/label/component/node-label-rotate.tsx
  stories/label/interaction.stories.tsx
  tests/unit/graph/controller/state-spec.ts
  types/index.ts
Labels: PR: unreviewed, bug

#1146 feat: update package version number
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, enhancement

#1144 fix: polyline problem
  src/layout/dagre.ts
  src/plugins/menu/index.ts
  src/shape/edge.ts
  src/shape/edges/polyline.ts
  src/shape/node.ts
  src/shape/nodes/circle.ts
  src/shape/nodes/star.ts
  src/util/index.ts
  tests/unit/behavior/drag-canvas-spec.ts
  tests/unit/layout/dagre-spec.ts
  tests/unit/shape/edges/polyline-spec.ts
Labels: PR: unreviewed, bug

#1150 fix: update g version number
  package.json
  src/behavior/drag-canvas.ts
  src/behavior/drag-node.ts
  tests/unit/behavior/drag-node-spec.ts
  tests/unit/behavior/index-spec.ts
Labels: PR: unreviewed, bug

#1151 fix: treegraph updatelayout
  package.json
  src/graph/tree-graph.ts
Labels: PR: reviewed-changes-requested, bug

#1160 fix: update main path
  package.json
  src/global.ts
Labels: PR: reviewed-changes-requested, bug
