Repository antvis/G6, pull requests merged in 2020-06, with the labels that each got.

#1577 refactor: use ml-matrix for the mds layout instead of numericJS
  global.d.ts
  package.json
  src/layout/mds.ts
  src/layout/radial/mds.ts
  tests/unit/graph/svg-spec.ts
Labels: PR: unreviewed, refactor

#1654 fix: 不能设置不存在的状态
  package.json
  src/graph/controller/item.ts
  tests/unit/behavior/activate-relations-spec.ts
  tests/unit/behavior/brush-select-spec.ts
  tests/unit/behavior/select-spec.ts
  tests/unit/combo-issue-spec.ts
  tests/unit/graph/controller/item-spec.ts
  tests/unit/graph/controller/state-spec.ts
  tests/unit/graph/graph-spec.ts
  tests/unit/graph/svg-spec.ts
  tests/unit/issues-spec.ts
Labels: PR: unreviewed, bug

#1685 Custom layout ticking
  src/graph/controller/layout.ts
Labels: PR: reviewed-changes-requested

#1695 docs: opt?-->edge
  docs/manual/tutorial/elements.zh.md
Labels: PR: unreviewed, documentation

#1720 docs: fix gallery demo url
  package.json
Labels: PR: unreviewed, documentation

#1721 fix: keyshape states bug & add tree demo
  examples/tree/customItemTree/demo/customEdgeTree.js
  examples/tree/customItemTree/demo/meta.json
  examples/tree/customItemTree/index.en.md
  examples/tree/customItemTree/index.zh.md
  package.json
  src/shape/shapeBase.ts
  src/types/index.ts
  stories/Layout/component/dagre-layout.tsx
  stories/Tree/component/flow-component.tsx
  stories/Tree/component/flow-tree.tsx
  stories/Tree/tree.stories.tsx
  tests/unit/issues-spec.ts
Labels: PR: unreviewed, bug
