Repository antvis/G6, pull requests merged in 2020-04, with the labels that each got.

#1412 docs: update the docs about state, custom node and urls of animate docs.
  docs/api/Group.en.md
  docs/api/Group.zh.md
  docs/manual/FAQ/transform.en.md
  docs/manual/FAQ/transform.zh.md
  docs/manual/advanced/custom-node.en.md
  docs/manual/advanced/custom-node.zh.md
  docs/manual/middle/states/state.zh.md
  examples/scatter/edge/index.en.md
  examples/scatter/edge/index.zh.md
  examples/scatter/node/demo/node.js
Labels: PR: reviewed-changes-requested, documentation

#1414 feat: set offset as a option in tooltip
  src/behavior/edge-tooltip.ts
  src/behavior/tooltip-base.ts
  src/behavior/tooltip.ts
Labels: PR: reviewed-changes-requested, enhancement

#1354 feat: add label background
  .vscode/settings.json
  src/shape/edge.ts
  src/shape/node.ts
  src/shape/shapeBase.ts
  src/types/index.ts
  stories/label/component/edge-label-background.tsx
  stories/label/interaction.stories.tsx
  tests/unit/shape/nodes/diamond-spec.ts
Labels: PR: unreviewed, enhancement

#1417 Combo update tree
  src/graph/graph.ts
  src/interface/item.ts
  src/item/item.ts
  src/item/node.ts
  src/util/graphic.ts
  stories/Combo/component/default-combo.tsx
Labels: PR: reviewed-changes-requested

#1422 Combo render
  src/graph/graph.ts
  src/interface/item.ts
  src/item/item.ts
  src/item/node.ts
  src/util/graphic.ts
  stories/Combo/component/default-combo.tsx
Labels: PR: unreviewed

#1431 fix: minimap viewport displace problem. feat: better performance of m…
  package.json
  src/behavior/drag-canvas.ts
  src/graph/graph.ts
  src/plugins/minimap/index.ts
  stories/Plugins/component/minimap-force.tsx
  stories/Plugins/component/minimap.tsx
  stories/Plugins/plugins.stories.tsx
  tests/unit/graph/svg-spec.ts
  tests/unit/plugins/minimap-spec.ts
Labels: PR: unreviewed, bug

#1430 feat: drag-combo
  package.json
  src/behavior/drag-combo.ts
  src/behavior/index.ts
  src/graph/graph.ts
  src/interface/graph.ts
  src/item/combo.ts
  src/types/index.ts
  src/util/base.ts
  src/util/graphic.ts
  stories/Issues/forceLayout/data.json
  stories/Issues/forceLayout/index.tsx
  stories/Issues/issues.stories.tsx
  tests/unit/behavior/drag-combo-spec.ts
  tests/unit/util/graphic-spec.ts
Labels: PR: unreviewed, enhancement

#1441 3.4.5 changelog
  CHANGELOG.md
Labels: PR: unreviewed

#1449 docs: update the docs for DOM listener.
  docs/manual/advanced/custom-node.en.md
  docs/manual/advanced/custom-node.zh.md
  examples/shape/customNode/demo/svgDom.js
  stories/Issues/component/dom-click.tsx
  stories/Issues/issues.stories.tsx
Labels: PR: reviewed-changes-requested, documentation

#1451 fix: dragging is not supported by clicking the label in the modelrect node
  src/shape/nodes/modelRect.ts
Labels: PR: reviewed-changes-requested, bug

#1467 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: unreviewed, chore

#1472 fix: 修复数据问题
  demos/case-voucher-transfer.html
  examples/case/decisionTree/demo/index.ts
  stories/Issues/attrs/index.tsx
  stories/Issues/changeData/data.js
  stories/Issues/changeData/index.tsx
  stories/Issues/component/dagre-arrow.tsx
  stories/Layout/component/dagre-layout.tsx
  stories/Shape/component/issue-1.tsx
  stories/Shape/component/polyline.tsx
  stories/Shape/component/quadratic.tsx
  stories/Tree/component/flow-tree.tsx
Labels: PR: reviewed-changes-requested, bug

#1473 fix: add security check file.
  .github/workflows/gitleaks.yml
Labels: PR: unreviewed, bug

#1503 fix: reconstructTree without parentId.
  src/behavior/drag-combo.ts
  src/graph/graph.ts
  src/util/graphic.ts
  stories/Combo/combo.stories.tsx
  stories/Combo/component/collapse-expand-vedge.tsx
  stories/Combo/component/combo-drag-collapse-expand.tsx
  stories/Combo/component/combo-layout-collapse-expand.tsx
Labels: PR: reviewed-changes-requested, bug

#1511 fix: expand combo with dulplicate virtual edges bug.
  src/graph/graph.ts
Labels: PR: reviewed-changes-requested, bug
