Repository antvis/G6, pull requests merged in 2020-09, with the labels that each got.

#2034 docs: update tooltip demos.
  examples/tool/tooltip/demo/meta.json
  examples/tool/tooltip/demo/tooltipLocal.js
  examples/tool/tooltip/demo/tooltipLocalCustom.js
  examples/tool/tooltip/demo/tooltipPluginLocal.js
  gatsby-config.js
Labels: PR: unreviewed, documentation

#2094 Chinese to English translation
  docs/manual/middle/overview.en.md
Labels: PR: unreviewed

#2098 fix: update G to fix the shape disappear when it has been dragged out…
  CHANGELOG.md
  package.json
  src/global.ts
  src/graph/graph.ts
  src/graph/tree-graph.ts
  stories/Plugins/component/toolbar.tsx
  tests/unit/graph/graph-spec.ts
  tests/unit/plugins/toolbar-spec.ts
Labels: PR: unreviewed, bug

#2116 feat: slice type timebar and tooltp for timebar.
  src/plugins/timeBar/timeBarSlice.ts
  src/plugins/timeBar/timeBarTooltip.ts
  stories/Plugins/component/timebar-slice.tsx
  stories/Plugins/component/timebar.tsx
  stories/Plugins/plugins.stories.tsx
Labels: PR: unreviewed, enhancement

#2092 feat: jsx node extend config support and next style
  examples/item/customNode/demo/xmlNode.js
  src/interface/shape.ts
  src/shape/shape.ts
  src/shape/xml.ts
  stories/Shape/component/xml.tsx
  stories/Shape/shape.stories.tsx
  tests/unit/shape/nodes/xml-spec.ts
Labels: PR: unreviewed, enhancement

#2107 Update animation.zh.md
  docs/manual/middle/animation.zh.md
Labels: PR: unreviewed

#2003 fix: polyline
  src/shape/edges/polyline-util.ts
  src/shape/edges/polyline.ts
  src/shape/edges/router.ts
  stories/Layout/component/dagre-layout.tsx
  stories/Shape/component/polyline-combo.tsx
  stories/Shape/component/polyline.tsx
  stories/Shape/shape.stories.tsx
  tests/unit/shape/edges/polyline-spec.ts
Labels: PR: unreviewed, bug

#2126 feat: add docs and jsx option in register
  docs/manual/middle/elements/nodes/jsx-node.en.md
  docs/manual/middle/elements/nodes/jsx-node.zh.md
  examples/item/customNode/demo/jsxNodeWithAnimate.js
  examples/item/customNode/demo/meta.json
  src/shape/shape.ts
Labels: PR: unreviewed, enhancement
