Repository antvis/G6, pull requests merged in 2020-02, with the labels that each got.

#1169 fix: change group.attr into group.set in item.ts
  src/item/item.ts
Labels: PR: unreviewed, bug

#1172 fix: update IMode define
  src/interface/graph.ts
Labels: PR: reviewed-changes-requested, bug

#1152 fix: site demos problem. add: radial sort site demo
  docs/manual/advanced/custom-node.en.md
  docs/manual/advanced/custom-node.zh.md
  docs/manual/cases/edgeBundling.en.md
  docs/manual/cases/edgeBundling.zh.md
  examples/case/christmasBubbles/demo/christmasBubbles.js
  examples/case/customFlow/demo/customFlow.js
  examples/case/decisionBubbles/demo/decisionBubbles.js
  examples/net/dagreFlow/demo/basicDagre.js
  examples/net/radialLayout/demo/interactRadial.js
  examples/net/radialLayout/demo/meta.json
  examples/net/radialLayout/demo/sortRadial.js
  examples/net/radialLayout/index.en.md
  examples/net/radialLayout/index.zh.md
  examples/shape/basic/demo/modelRect.js
  examples/tool/contextMenu/demo/contextMenu.js
  examples/tree/customItemTree/demo/customTree.js
  examples/tree/customItemTree/demo/treeWithLargeData.js
  stories/Case/component/decision-tree.tsx
  stories/Tree/component/large-data.tsx
Labels: PR: reviewed-changes-requested, bug

#1179 fix: 修复 IGraph 中find 和 findall 第二个参数为可选
  package.json
  src/global.ts
  src/interface/graph.ts
Labels: PR: unreviewed, bug

#1180 Fix types file
  package.json
  src/global.ts
Labels: PR: unreviewed

#1176 修复 strict: true 下 TS 错误：src/graph
  src/graph/controller/event.ts
  src/graph/controller/item.ts
  src/graph/controller/mode.ts
  src/graph/controller/state.ts
  src/graph/controller/view.ts
  src/graph/graph.ts
  src/graph/tree-graph.ts
  src/interface/graph.ts
  src/interface/item.ts
  src/plugins/bundling/index.ts
  src/types/index.ts
Labels: PR: unreviewed, strict

#1181 fix: ensure do not expand dom Node in updateItem
  src/graph/controller/item.js
Labels: PR: reviewed-approved, bug

#1185 fix: filter html node
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, bug

#1188 fix: export plugins and they can be called by G6.Minimap and so on.
  package.json
  src/index.ts
  tests/unit/plugins/bundling-spec.ts
  tests/unit/plugins/grid-spec.ts
  tests/unit/plugins/menu-spec.ts
  tests/unit/plugins/minimap-spec.ts
Labels: PR: unreviewed, bug

#1191 fix: optimize the performance
  package.json
  src/graph/graph.ts
  src/graph/tree-graph.ts
  src/interface/graph.ts
  src/interface/shape.ts
  src/shape/edge.ts
  src/shape/edges/polyline.ts
  src/shape/node.ts
  src/shape/nodes/circle.ts
  src/shape/nodes/diamond.ts
  src/shape/nodes/ellipse.ts
  src/shape/nodes/modelRect.ts
  src/shape/nodes/rect.ts
  src/shape/nodes/star.ts
  src/shape/nodes/triangle.ts
  src/shape/shapeBase.ts
  src/types/index.ts
  stories/Performance/component/complex-tree.tsx
  stories/Performance/component/erdos.tsx
  stories/Performance/component/eva.tsx
  stories/Performance/component/netscience.tsx
  stories/Performance/component/rt-occupy.tsx
  stories/Performance/performance.stories.tsx
  tests/unit/graph/tree-graph-spec.ts
  tests/unit/shape/nodes/modelRect-spec.ts
  tests/unit/shape/nodes/star-spec.ts
Labels: PR: unreviewed, bug

#1193 修复 src/graph 和 src/behavior 的 ESLint Error
  .eslintrc.js
  src/behavior/activate-relations.ts
  src/behavior/behavior.ts
  src/behavior/behaviorOption.ts
  src/behavior/brush-select.ts
  src/behavior/click-select.ts
  src/behavior/collapse-expand-group.ts
  src/behavior/collapse-expand.ts
  src/behavior/drag-canvas.ts
  src/behavior/drag-group.ts
  src/behavior/drag-node-with-group.ts
  src/behavior/drag-node.ts
  src/behavior/edge-tooltip.ts
  src/behavior/tooltip-base.ts
  src/behavior/zoom-canvas.ts
  src/graph/controller/customGroup.ts
  src/graph/controller/event.ts
  src/graph/controller/item.ts
  src/graph/controller/layout.ts
  src/graph/controller/mode.ts
  src/graph/controller/state.ts
  src/graph/controller/view.ts
  src/graph/graph.ts
  src/graph/tree-graph.ts
  src/layout/grid.ts
  src/layout/radial/radial.ts
  src/util/base.ts
Labels: PR: unreviewed

#1195 fix: refactor eslint
  .eslintrc.js
  src/item/edge.ts
  src/item/item.ts
  src/layout/mds.ts
  src/plugins/bundling/index.ts
  src/plugins/menu/index.ts
  src/plugins/minimap/index.ts
  src/shape/shapeBase.ts
  src/util/group.ts
  src/util/math.ts
  src/util/path.ts
Labels: PR: reviewed-changes-requested, bug

#1196 fix: ts eslint error
  .eslintrc.js
  src/layout/circular.ts
  src/layout/force.ts
  src/layout/grid.ts
  src/layout/layout.ts
  src/layout/radial/radial.ts
  src/util/math.ts
Labels: PR: reviewed-changes-requested, bug

#1197 feat: update package version number
  CHANGELOG.md
  package.json
  src/global.ts
Labels: PR: reviewed-changes-requested, enhancement

#1198 docs: add upgrade-guidance. feat: switch different versions site. fix…
  docs/manual/FAQ/build-error.en.md
  docs/manual/FAQ/build-error.zh.md
  docs/manual/FAQ/front-edge.en.md
  docs/manual/FAQ/front-edge.zh.md
  docs/manual/FAQ/gradient.en.md
  docs/manual/FAQ/gradient.zh.md
  docs/manual/FAQ/multi-line.en.md
  docs/manual/FAQ/multi-line.zh.md
  docs/manual/FAQ/supportIE.en.md
  docs/manual/FAQ/supportIE.zh.md
  docs/manual/FAQ/texture.en.md
  docs/manual/FAQ/texture.zh.md
  docs/manual/FAQ/transform.en.md
  docs/manual/FAQ/transform.zh.md
  docs/manual/FAQ/updateElement.en.md
  docs/manual/FAQ/updateElement.zh.md
  docs/manual/FAQ/updateText.en.md
  docs/manual/FAQ/updateText.zh.md
  docs/manual/FAQ/upgradeGuide.en.md
  docs/manual/FAQ/upgradeGuide.zh.md
  gatsby-config.js
  package.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested, documentation

#1199 feat: multiple version of sites
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, enhancement

#1202 feat: readme show coverage info
  README-zh_CN.md
  README.md
Labels: PR: unreviewed, enhancement

#1208 Update introduction.en.md
  docs/manual/introduction.en.md
Labels: PR: unreviewed

#1217 fix: 修正拼写错误
  tests/unit/graph/controller/mode-spec.ts
Labels: bug

#1220 fix: 更新升级文档
  docs/manual/FAQ/upgradeGuide.en.md
  docs/manual/FAQ/upgradeGuide.zh.md
Labels: bug

#1221 refactor: fix TypeScript type error
  src/index.ts
Labels: refactor

#1241 feat: add weight field for dagre layout
  src/layout/dagre.ts
Labels: enhancement
