Repository antvis/G6, pull requests merged in 2020-07, with the labels that each got.

#1779 fix: links in doc
  docs/api/nodeEdge/itemProperties.zh.md
  docs/manual/advanced/custom-combo.en.md
  docs/manual/advanced/custom-combo.zh.md
  docs/manual/advanced/keyconcept/graphics-group.en.md
  docs/manual/middle/Plugins.en.md
  docs/manual/middle/Plugins.zh.md
  docs/manual/middle/combo.en.md
  docs/manual/middle/elements/anchorpoint.en.md
  docs/manual/middle/elements/anchorpoint.zh.md
  docs/manual/middle/elements/edges/arc.zh.md
  docs/manual/middle/elements/edges/cubic.zh.md
  docs/manual/middle/elements/edges/line.zh.md
  docs/manual/middle/elements/edges/loop.zh.md
  docs/manual/middle/elements/edges/polyline.zh.md
  docs/manual/middle/elements/edges/quadratic.zh.md
  docs/manual/middle/graph.en.md
  docs/manual/middle/nodeGroup.en.md
  docs/manual/middle/svg.en.md
  examples/interaction/customBehavior/index.en.md
  examples/interaction/customBehavior/index.zh.md
  examples/interaction/moveSubtree/index.zh.md
  examples/net/circular/index.en.md
  examples/net/concentricLayout/index.en.md
  examples/net/dagreFlow/index.en.md
  examples/net/forceDirected/index.en.md
  examples/net/furchtermanLayout/index.en.md
  examples/net/gridLayout/index.en.md
Labels: PR: unreviewed, bug

#1778 fix: lose the state style
  src/shape/shapeBase.ts
  stories/Shape/component/loseStateStyle.tsx
  stories/Shape/shape.stories.tsx
Labels: PR: reviewed-changes-requested, bug

#1781 docs: fix graphics group doc; add setClip method in doc
  docs/api/Custom.en.md
  docs/api/Custom.zh.md
  docs/api/Group.en.md
  docs/api/Group.zh.md
  docs/api/nodeEdge/Item.en.md
  docs/api/nodeEdge/Item.zh.md
  docs/api/nodeEdge/shapeProperties.en.md
  docs/api/nodeEdge/shapeProperties.zh.md
  docs/manual/advanced/custom-combo.en.md
  docs/manual/advanced/custom-combo.zh.md
  docs/manual/advanced/custom-node.en.md
  docs/manual/advanced/custom-node.zh.md
  docs/manual/advanced/keyconcept/graphics-group.en.md
  docs/manual/advanced/keyconcept/graphics-group.zh.md
Labels: PR: unreviewed, documentation

#1782 fix: remove lodash dependencies
  package.json
  src/graph/graph.ts
  stories/Issues/changeData/index.tsx
  stories/Issues/ggeditorNode/baseNode.ts
  tests/unit/graph/controller/customGroup-spec.ts
Labels: PR: unreviewed, bug

#1796 docs: fix customBehavior demo
  examples/interaction/customBehavior/demo/dragCanvasTwoFingers.js
  examples/interaction/customBehavior/index.en.md
  examples/interaction/customBehavior/index.zh.md
Labels: PR: reviewed-changes-requested, documentation

#1795 docs: uniform AntV navbar's order and naming
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, documentation

#1819 fix: drag new node without initial position
  package.json
  src/behavior/drag-node.ts
  src/graph/controller/item.ts
  tests/unit/behavior/drag-node-spec.ts
Labels: PR: unreviewed, bug

#1816 docs: fix contextmenu demo
  examples/tool/contextMenu/demo/contextMenu.js
Labels: PR: reviewed-changes-requested, documentation

#1842 docs: add docs for lasso behavior
  docs/api/Event.en.md
  docs/api/Event.zh.md
  docs/manual/middle/states/defaultBehavior.en.md
  docs/manual/middle/states/defaultBehavior.zh.md
Labels: PR: unreviewed, documentation

#1851 fix: add isPolygonsIntersect in math util & remove its dependency of …
  src/behavior/lasso-select.ts
  src/util/math.ts
Labels: PR: reviewed-changes-requested, bug

#1850 docs: add docs for getAdjMatrix, getShortestPathMatrix; add doc for l…
  docs/api/Graph.en.md
  docs/api/Graph.zh.md
  docs/manual/middle/states/defaultBehavior.en.md
  docs/manual/middle/states/defaultBehavior.zh.md
Labels: PR: unreviewed, documentation

#1852 docs: add docs for getNeighbors
  docs/api/Graph.en.md
  docs/api/Graph.zh.md
  docs/api/nodeEdge/Node.en.md
  docs/api/nodeEdge/Node.zh.md
Labels: PR: unreviewed, documentation
