Repository antvis/G6, pull requests merged in 2023-04, with the labels that each got.

#4411 fix: tooltip top position error #4410
  packages/plugin/src/tooltip/index.ts
Labels: PR: unreviewed

#4398 fix: type for draw function in elements, closes: #4395
  CHANGELOG.md
  packages/core/package.json
  packages/core/src/global.ts
  packages/core/src/interface/shape.ts
  packages/element/package.json
  packages/g6/package.json
  packages/g6/src/index.ts
  packages/pc/package.json
  packages/pc/src/global.ts
  packages/pc/src/graph/tree-graph.ts
  packages/pc/src/layout/worker/layout.ts
  packages/plugin/package.json
  packages/plugin/src/timeBar/index.ts
  packages/plugin/src/tooltip/index.ts
  packages/site/docs/manual/middle/elements/combos/custom-combo.en.md
  packages/site/docs/manual/middle/elements/combos/custom-combo.zh.md
  packages/site/examples/interaction/combo/demo/cRect.js
  packages/site/examples/item/customCombo/demo/cRect.js
Labels: PR: unreviewed

#4380 feat: activate relations
  package.json
  packages/g6/package.json
  packages/g6/src/runtime/controller/data.ts
  packages/g6/src/stdlib/behavior/activate-relations.ts
  packages/g6/src/stdlib/index.ts
  packages/g6/src/types/index.ts
  packages/g6/tests/datasets/const.ts
  packages/g6/tests/index.html
  packages/g6/tests/intergration/behaviors/activate-relations.ts
  packages/g6/tests/intergration/behaviors/brush-select.ts
  packages/g6/tests/intergration/behaviors/click-select.ts
  packages/g6/tests/intergration/index.ts
  packages/g6/tests/intergration/layouts/circular.ts
  packages/g6/tests/main.ts
  packages/g6/vite.config.js
Labels: PR: partially-approved

#4390 feat: plugin controller and base; feat: minimap;
  packages/g6/.prettierrc
  packages/g6/jest.config.js
  packages/g6/package.json
  packages/g6/src/constant/shape.ts
  packages/g6/src/item/item.ts
  packages/g6/src/runtime/controller/data.ts
  packages/g6/src/runtime/controller/item.ts
  packages/g6/src/runtime/controller/plugin.ts
  packages/g6/src/runtime/controller/viewport.ts
  packages/g6/src/runtime/graph.ts
  packages/g6/src/stdlib/behavior/brush-select.ts
  packages/g6/src/stdlib/index.ts
  packages/g6/src/stdlib/plugin/legend/index.ts
  packages/g6/src/stdlib/plugin/minimap/index.ts
  packages/g6/src/types/graph.ts
  packages/g6/src/types/hook.ts
  packages/g6/src/types/plugin.ts
  packages/g6/src/types/spec.ts
  packages/g6/src/util/array.ts
  packages/g6/src/util/canvas.ts
  packages/g6/src/util/shape.ts
  packages/g6/tests/unit/plugins/legend-spec.ts
  packages/g6/tests/unit/plugins/minimap-spec.ts
Labels: PR: unreviewed

#4449 fix: tests
  packages/g6/package.json
  packages/g6/src/runtime/controller/interaction.ts
  packages/g6/src/stdlib/behavior/brush-select.ts
  packages/g6/src/stdlib/behavior/lasso-select.ts
  packages/g6/tests/unit/behaviors/brush-select-spec.ts
  packages/g6/tests/unit/behaviors/lasso-select-spec.ts
  packages/g6/tests/unit/item-spec.ts
  packages/g6/tests/unit/plugins/legend-spec.ts
  packages/g6/tests/unit/plugins/minimap-spec.ts
  packages/g6/tests/unit/theme-subject-spec.ts
  packages/g6/tests/unit/util.ts
  packages/g6/tests/unit/view-spec.ts
Labels: PR: reviewed-approved

#4453 fix: update layout from animate false to true;
  CHANGELOG.md
  packages/core/package.json
  packages/core/src/global.ts
  packages/element/package.json
  packages/g6/package.json
  packages/g6/src/index.ts
  packages/pc/package.json
  packages/pc/src/global.ts
  packages/pc/src/graph/controller/layout.ts
  packages/plugin/package.json
Labels: PR: unreviewed

#4450 feat: drag-canvas behavior
  packages/g6/package.json
  packages/g6/src/item/edge.ts
  packages/g6/src/item/item.ts
  packages/g6/src/item/node.ts
  packages/g6/src/runtime/controller/item.ts
  packages/g6/src/runtime/graph.ts
  packages/g6/src/stdlib/behavior/drag-canvas.ts
  packages/g6/src/stdlib/behavior/zoom-canvas.ts
  packages/g6/src/stdlib/index.ts
  packages/g6/src/util/item.ts
  packages/g6/tests/unit/behaviors/drag-canvas-spec.ts
  packages/g6/tests/unit/behaviors/zoom-canvas-spec.ts
Labels: PR: reviewed-approved

#4454 docs: 修复文档表格展示错误问题
  packages/site/docs/manual/middle/elements/nodes/built-in/image.en.md
  packages/site/docs/manual/middle/elements/nodes/built-in/image.zh.md
  packages/site/docs/manual/middle/elements/nodes/built-in/modelRect.en.md
  packages/site/docs/manual/middle/elements/nodes/built-in/modelRect.zh.md
  packages/site/docs/manual/middle/elements/nodes/built-in/rect.zh.md
  packages/site/docs/manual/middle/elements/nodes/built-in/star.en.md
  packages/site/docs/manual/middle/elements/nodes/built-in/star.zh.md
  packages/site/docs/manual/middle/elements/nodes/built-in/triangle.en.md
  packages/site/docs/manual/middle/elements/nodes/built-in/triangle.zh.md
Labels: PR: unreviewed

#4470 feat: style standards; perf: type refine
  packages/g6/src/constant/shape.ts
  packages/g6/src/item/edge.ts
  packages/g6/src/item/item.ts
  packages/g6/src/item/node.ts
  packages/g6/src/runtime/controller/data.ts
  packages/g6/src/runtime/controller/item.ts
  packages/g6/src/stdlib/item/edge/base.ts
  packages/g6/src/stdlib/item/edge/line.ts
  packages/g6/src/stdlib/item/node/base.ts
  packages/g6/src/stdlib/item/node/base3d.ts
  packages/g6/src/stdlib/item/node/circle.ts
  packages/g6/src/stdlib/item/node/sphere.ts
  packages/g6/src/stdlib/theme/dark.ts
  packages/g6/src/stdlib/theme/light.ts
  packages/g6/src/stdlib/themeSolver/spec.ts
  packages/g6/src/types/combo.ts
  packages/g6/src/types/edge.ts
  packages/g6/src/types/item.ts
  packages/g6/src/types/node.ts
  packages/g6/src/types/theme.ts
  packages/g6/src/util/mapper.ts
  packages/g6/src/util/math.ts
  packages/g6/src/util/point.ts
  packages/g6/src/util/shape.ts
  packages/g6/src/util/shape3d.ts
  packages/g6/tests/main.ts
  packages/g6/tests/unit/behaviors/lasso-select-spec.ts
  packages/g6/tests/unit/edge-spec.ts
  packages/g6/tests/unit/item-3d-spec.ts
  packages/g6/tests/unit/node-spec.ts
  packages/g6/tests/unit/theme-spec.ts
Labels: PR: reviewed-approved
