Repository antvis/G6, pull requests merged in 2024-04, with the labels that each got.

#5605 feat: history plugin
  .vscode/settings.json
  packages/g6/__tests__/demos/index.ts
  packages/g6/__tests__/demos/plugin-history.ts
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/addData-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/addData-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/addData.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/collapse-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/collapse-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/collapse.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/deleteData-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/deleteData-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/deleteData.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/expand-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/expand-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/expand.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/hideElement.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementZIndex.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementsState-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementsState-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/setElementsState.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/updateData-redo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/updateData-undo.svg
  packages/g6/__tests__/snapshots/plugins/history/plugin-history/updateData.svg
  packages/g6/__tests__/unit/plugins/history/plugin-history.spec.ts
  packages/g6/__tests__/unit/plugins/history/utils.spec.ts
  packages/g6/__tests__/unit/utils/animation.spec.ts
  packages/g6/__tests__/unit/utils/id.spec.ts
  packages/g6/src/behaviors/drag-element.ts
  packages/g6/src/behaviors/hover-element.ts
  packages/g6/src/constants/events/graph.ts
  packages/g6/src/exports.ts
  packages/g6/src/plugins/history/events.ts
  packages/g6/src/plugins/history/index.ts
  packages/g6/src/plugins/history/utils.ts
  packages/g6/src/plugins/index.ts
  packages/g6/src/registry/build-in.ts
  packages/g6/src/runtime/batch.ts
  packages/g6/src/runtime/data.ts
  packages/g6/src/runtime/element.ts
  packages/g6/src/runtime/graph.ts
  packages/g6/src/runtime/types.ts
  packages/g6/src/types/change.ts
  packages/g6/src/utils/animation.ts
  packages/g6/src/utils/change.ts
  packages/g6/src/utils/event/events.ts
  packages/g6/src/utils/id.ts
  packages/g6/src/utils/style.ts
  packages/site/examples/tool/history/demo/default.ts
  packages/site/examples/tool/history/demo/meta.json
  packages/site/examples/tool/history/index.en.md
  packages/site/examples/tool/history/index.zh.md
Labels: size:L, lgtm

#5636 feat: add click-element behavior
  packages/g6/__tests__/demos/behavior-click-element.ts
  packages/g6/__tests__/demos/behavior-hover-element.ts
  packages/g6/__tests__/demos/index.ts
  packages/g6/__tests__/snapshots/behaviors/click-element/after-deselect.svg
  packages/g6/__tests__/snapshots/behaviors/click-element/after-select.svg
  packages/g6/__tests__/snapshots/behaviors/click-element/custom-state.svg
  packages/g6/__tests__/snapshots/behaviors/click-element/default.svg
  packages/g6/__tests__/snapshots/behaviors/click-element/edge-1-degree.svg
  packages/g6/__tests__/snapshots/behaviors/click-element/multiple-meta.svg
  packages/g6/__tests__/snapshots/behaviors/click-element/multiple-shift.svg
  packages/g6/__tests__/snapshots/behaviors/click-element/node-1-degree.svg
  packages/g6/__tests__/unit/behaviors/click-element.spec.ts
  packages/g6/src/behaviors/click-element.ts
  packages/g6/src/behaviors/index.ts
  packages/g6/src/registry/build-in.ts
  packages/site/examples/interaction/select/demo/click.js
  packages/site/examples/interaction/select/demo/click.ts
  packages/site/examples/interaction/select/demo/meta.json
Labels: documentation, Feat, test, example, AntV OSCP, size:L, lgtm

#5641 feat(runtime): add transform controller
  packages/g6/__tests__/unit/runtime/graph/graph.spec.ts
  packages/g6/src/constants/change.ts
  packages/g6/src/constants/events/graph.ts
  packages/g6/src/constants/registry.ts
  packages/g6/src/exports.ts
  packages/g6/src/registry/build-in.ts
  packages/g6/src/registry/extension/index.ts
  packages/g6/src/registry/index.ts
  packages/g6/src/registry/types.ts
  packages/g6/src/runtime/behavior.ts
  packages/g6/src/runtime/data.ts
  packages/g6/src/runtime/element.ts
  packages/g6/src/runtime/graph.ts
  packages/g6/src/runtime/plugin.ts
  packages/g6/src/runtime/transform.ts
  packages/g6/src/runtime/types.ts
  packages/g6/src/spec/index.ts
  packages/g6/src/spec/spec.ts
  packages/g6/src/spec/transform.ts
  packages/g6/src/transforms/arrange-draw-order.ts
  packages/g6/src/transforms/base-transform.ts
  packages/g6/src/transforms/collapse-expand-combo.ts
  packages/g6/src/transforms/index.ts
  packages/g6/src/transforms/types.ts
  packages/g6/src/transforms/update-related-edge.ts
  packages/g6/src/types/change.ts
  packages/g6/src/utils/change.ts
  packages/g6/src/utils/extension.ts
Labels: Feat, size:XL, lgtm

#5646 test: add demo that use imported svg as node icon
  packages/g6/__tests__/assets/comment.svg
  packages/g6/__tests__/assets/user.svg
  packages/g6/__tests__/demos/element-node-svg-icon.ts
  packages/g6/__tests__/demos/index.ts
  packages/g6/__tests__/types.d.ts
  packages/g6/__tests__/utils/svg-transformer.js
  packages/g6/jest.config.js
Labels: test, size:M, lgtm

#5643 feat(transform): process parallel edges (bundle, merge)
  packages/g6/__tests__/dataset/parallel-edges.json
  packages/g6/__tests__/demos/index.ts
  packages/g6/__tests__/demos/transform-process-parallel-edges.ts
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/bundle-add-orange-edge__after.svg
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/bundle-add-orange-edge__before.svg
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/bundle-mode.svg
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/bundle-remove-purple-edge__after.svg
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/bundle-remove-purple-edge__before.svg
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/bundle-update-orange-edge__after.svg
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/bundle-update-orange-edge__before.svg
  packages/g6/__tests__/snapshots/transforms/transform-process-parallel-edges/merge-mode.svg
  packages/g6/__tests__/unit/runtime/data.spec.ts
  packages/g6/__tests__/unit/transforms/transform-process-parallel-edges.spec.ts
  packages/g6/src/registry/build-in.ts
  packages/g6/src/runtime/data.ts
  packages/g6/src/runtime/element.ts
  packages/g6/src/transforms/index.ts
  packages/g6/src/transforms/process-parallel-edges.ts
  packages/g6/src/transforms/update-related-edge.ts
  packages/site/examples/item/multiEdge/demo/meta.json
  packages/site/examples/item/multiEdge/demo/multiEdges.js
  packages/site/examples/item/multiEdge/demo/multiEdges.ts
Labels: Feat, size:XL, lgtm

#5649 fix: fix types of elements
  packages/g6-extension-3d/src/elements/base-node-3d.ts
  packages/g6/src/behaviors/brush-select.ts
  packages/g6/src/elements/combos/base-combo.ts
  packages/g6/src/elements/combos/circle.ts
  packages/g6/src/elements/combos/rect.ts
  packages/g6/src/elements/edges/base-edge.ts
  packages/g6/src/elements/edges/cubic-horizontal.ts
  packages/g6/src/elements/edges/cubic-vertical.ts
  packages/g6/src/elements/edges/cubic.ts
  packages/g6/src/elements/edges/polyline.ts
  packages/g6/src/elements/edges/quadratic.ts
  packages/g6/src/elements/nodes/base-node.ts
  packages/g6/src/elements/nodes/circle.ts
  packages/g6/src/elements/nodes/diamond.ts
  packages/g6/src/elements/nodes/ellipse.ts
  packages/g6/src/elements/nodes/hexagon.ts
  packages/g6/src/elements/nodes/image.ts
  packages/g6/src/elements/nodes/polygon.ts
  packages/g6/src/elements/nodes/rect.ts
  packages/g6/src/elements/nodes/star.ts
  packages/g6/src/elements/nodes/triangle.ts
  packages/g6/src/elements/types.ts
  packages/g6/src/runtime/data.ts
  packages/g6/src/runtime/element.ts
  packages/g6/src/runtime/layout.ts
  packages/g6/src/types/element.ts
  packages/g6/src/types/node.ts
  packages/g6/src/utils/combo.ts
  packages/g6/src/utils/prefix.ts
Labels: Fix, size:XL, lgtm

#5648 refactor: toDataURL support export overall mode
  packages/g6/__tests__/demos/graph-to-data-url.ts
  packages/g6/__tests__/snapshots/elements/position-combo/default.svg
  packages/g6/__tests__/snapshots/layouts/combo-layout/combined.svg
  packages/g6/__tests__/snapshots/layouts/compact-box/left-align.svg
  packages/g6/__tests__/snapshots/layouts/compact-box/top-to-bottom.svg
  packages/g6/__tests__/snapshots/layouts/dagre/antv-flow-combo.svg
  packages/g6/__tests__/snapshots/layouts/mindmap/h-left.svg
  packages/g6/__tests__/snapshots/layouts/mindmap/h-right.svg
  packages/g6/__tests__/snapshots/plugins/tooltip/edge.svg
  packages/g6/__tests__/snapshots/plugins/tooltip/hover.svg
  packages/g6/__tests__/snapshots/plugins/tooltip/node.svg
  packages/g6/__tests__/snapshots/plugins/tooltip/show-tooltip-by-id.svg
  packages/g6/__tests__/unit/runtime/graph/graph.spec.ts
  packages/g6/src/runtime/canvas.ts
  packages/g6/src/runtime/graph.ts
Labels: refactor, size:M, lgtm

#5650 chore: updater version to 5.0.0-beta.33
  packages/g6/package.json
Labels: chore, size:XS, lgtm

#5645 feat(element): add donut
  packages/g6/__tests__/demos/element-node-donut.ts
  packages/g6/__tests__/demos/index.ts
  packages/g6/__tests__/snapshots/elements/nodes/donut/default.svg
  packages/g6/__tests__/unit/elements/nodes/donut.spec.ts
  packages/g6/__tests__/unit/registry.spec.ts
  packages/g6/src/elements/nodes/donut.ts
  packages/g6/src/elements/nodes/index.ts
  packages/g6/src/exports.ts
  packages/g6/src/registry/build-in.ts
  packages/g6/src/themes/base.ts
  packages/site/docs/apis/item/node/DonutNode.en.md
  packages/site/docs/apis/item/node/DonutNode.zh.md
  packages/site/examples/item/defaultNodes/demo/donut.js
  packages/site/examples/item/defaultNodes/demo/donut.ts
  packages/site/examples/item/defaultNodes/demo/meta.json
Labels: Feat, size:XL
